name = "overpriseed"
main = "src/index.ts"
compatibility_date = "2024-12-20"

[env.production]
name = "overpriseed-production"

[[d1_databases]]
binding = "DB"
database_name = "overpriseed-db"
database_id = "bc5272b6-133e-49ba-bb19-adb1bca72816"